const BEDROCK_STUB = process.env.BEDROCK_STUB !== 'false';
const BEDROCK_MODEL_ID = process.env.BEDROCK_MODEL_ID || 'anthropic.claude-3-5-sonnet-20241022-v2:0';

/**
 * Generate a customized instructional activity using AWS Bedrock (Claude).
 * Stubbed locally with a deterministic template.
 */
async function generateActivity({ strategy, lessonTitle, grade, subject, categoryKey }) {
  if (BEDROCK_STUB) {
    return {
      activity: buildStubActivity({ strategy, lessonTitle, grade, subject, categoryKey }),
      aiGenerated: false,
      model: 'local-stub',
      source: 'bedrock-stub',
    };
  }

  try {
    const { BedrockRuntimeClient, InvokeModelCommand } = require('@aws-sdk/client-bedrock-runtime');
    const client = new BedrockRuntimeClient({ region: process.env.AWS_REGION || 'us-east-1' });

    const prompt = `You are an instructional coach helping a teacher improve student engagement.

Lesson: ${lessonTitle || 'Untitled'}
Grade: ${grade || 'not specified'}
Subject: ${subject || 'not specified'}
Engagement area to improve: ${categoryKey}
Strategy: ${strategy.title}
Goal: ${strategy.goal}
Steps: ${(strategy.steps || []).join('; ')}

Generate a specific, classroom-ready activity (150-250 words) the teacher can use in their next lesson. Include:
1. Activity title
2. Time needed
3. Step-by-step instructions
4. How it addresses the engagement gap

Do not include student names or PII.`;

    const body = JSON.stringify({
      anthropic_version: 'bedrock-2023-05-31',
      max_tokens: 600,
      messages: [{ role: 'user', content: prompt }],
    });

    const response = await client.send(new InvokeModelCommand({
      modelId: BEDROCK_MODEL_ID,
      contentType: 'application/json',
      accept: 'application/json',
      body,
    }));

    const parsed = JSON.parse(new TextDecoder().decode(response.body));
    const activity = parsed.content?.[0]?.text || 'Activity generation failed.';

    return {
      activity,
      aiGenerated: true,
      model: BEDROCK_MODEL_ID,
      source: 'bedrock',
    };
  } catch (err) {
    console.error('Bedrock generation failed, using stub:', err.message);
    return {
      activity: buildStubActivity({ strategy, lessonTitle, grade, subject, categoryKey }),
      aiGenerated: false,
      model: 'local-fallback',
      source: 'bedrock-fallback',
    };
  }
}

function buildStubActivity({ strategy, lessonTitle, categoryKey }) {
  return [
    `**Activity: ${strategy.title}**`,
    `*For lesson: ${lessonTitle || 'your next lesson'}*`,
    '',
    `**Time:** 10–15 minutes`,
    '',
    '**Instructions:**',
    ...(strategy.steps || []).map((step, i) => `${i + 1}. ${step}`),
    '',
    `This activity targets the **${categoryKey.replace(/_/g, ' ')}** engagement area.`,
    '',
    '_Generated by local stub. Set BEDROCK_STUB=false for Claude-powered activities._',
  ].join('\n');
}

module.exports = { generateActivity, BEDROCK_MODEL_ID };
